# Основная конфигурация (config.yml)

# Локация Спавна.
# Сюда будет попадать игрок при заходе на сервер,
# а также после респавна.
spawn:
    enabled: true
    # Принимает только названия варпов из warps.yml
    # Сообщения, привязанные к варпу выводиться не будут!
    warp: "hub"
# Скрытие частых сообщений
hideStream:
    # Скрыть ли сообщения о входе игрока?
    join: true
    # Скрыть ли сообщения о выходе игрока?
    exit: true
    # Скрыть ли сообщения о кике игрока?
    kick: true
    # Скрыть ли сообщения о смерти игрока?
    death: true
# Полезные плюшки
perks:
    # Сколько должно быть сердечек?
    maxHearts:
        enabled: true
        # 1 - половина сердечка, 20 - обычная шкала.
        value: 10
        # Восстанавливать ли здоровье до health при перезаходе?
        restore: false
    # Каков должен быть уровень сытости?
    foodLevel:
        enabled: true
        # 0 - полностью голодный, 20 - обычная шкала.
        value: 10
        # Если включено, то голод не будет тратиться,
        # а игрок не будет умирать даже с нулевой шкалой.
        # Однако, скорость всё равно будет теряться.
        infinite: true
    # Какова должна быть скорость передвижения?
    walkSpeed:
        enabled: true
        # Во сколько раз увеличить скорость игрока?
        # Принимает значения от -1.0 до 1.0
        # У игрока по умолчанию 0.2
        value: 0.3
    # Превращать ли всех сущностей в других?
    # Работает только в мирах, кроме Ада и Края!
    onlyMobs:
        enabled: true
        # В какой тип сущности превращать?
        type: "PIG"
        # Подделывать ли смерть сущности?
        # Тогда она умрёт без стандартной анимации
        # и не оставит дропа после смерти
        fakeDeath: true
        # Делать ли кровяной выброс после смерти?
        exudeBlood: true
    # Отключить ли PVP между игроками?
    preventFights:
        enabled: true
    # Отключать ли урон от падения?
    fallRescue:
        enabled: true
    # Спасать ли игроков, падающих в пустоту?
    voidRescue:
        enabled: true
        # Локация из warps.yml
        warp: "hub"
    # Разрешить ли игрокам заходить на заполненный сервер?
    overflowJoin:
        enabled: true
        # Количество видимых слотов.
        # Может быть любым числом, даже отрицательным.
        slots: -1
    # Последовательность приветствия:
    # 1. Режим Приключений
    # 2. Звук Получения опыта
    # К сожалению, доп. настройки отсутствуют,
    # можно только отключить совсем.
    welcomeSequence:
        # Проигрывать ли последовательность каждый раз
        # при заходе игрока на сервер?
        enabled: true
# Ограничения
limits:
    # Ограничение времени суток
    daylightCycle:
        enabled: true
        # В каких мирах отключить смену дня и ночи?
        worlds: ["world"]
    # Ограничение погоды
    weatherCycle:
        enabled: true
        # В каких мирах отключить смену погоды?
        worlds: ["world"]
    # Ограничение тиков
    tickSpeed:
        enabled: true
        # В каких мирах установить randomTickSpeed на 0?
        worlds: ["world"]
    # Ограничение достижений
    advancements:
        enabled: true
        # В каких мирах отключить достижения?
        worlds: ["world"]
    # Ограничение ИИ сущностей
    mobAi:
        enabled: false
        # В каких мирах отключить ИИ сущностей?
        worlds: ["world"]
    # Ограничение физики
    physics:
        enabled: true
        # В каких мирах ограничить физику?
        worlds: ["world"]
    # Ограничение порталов
    portals:
        enabled: true
        # В каких мирах отключить создание
        # и использование порталов?
        worlds: ["world"]
    # Ограничение взаимодействий с блоками
    blocks:
        enabled: true
        # В каких мирах отключить ломание/установку блоков,
        # различные взаимодействия с блоками (например,
        # открывание сундуков, печек и т.п.), гниение
        # (пропадание без древесины) листьев, а также
        # поджигание блоков и распространение огня по ним?
        worlds: ["world"]
    # Ограничение опыта
    experience:
        enabled: true
        # В каких мирах отключить получение опыта?
        worlds: ["world"]
# Консоль
console:
    # Логировать ли вход/выход игроков?
    logJoinAndQuit: true
    # Запрещает вывод сообщения, если в нём
    # содержится любая фраза из этого списка
    # НЕ чувствителен к регистру!
    filter:
        - "com.mojang.authlib.gameprofile"
        - "uuid of player"
        - "logged in with entity id"
        - "lost connection"
