name: RichWorld
author: KvaytG
main: ru.kvaytg.richworld.RichWorld
version: 1.0.0
api-version: 1.13
depend: [ColorAPI]
commands:
    kick:
        description: "Kick player. @all for the Console only"
        usage: "/kick <player|@all> <reason>"
    kill:
        description: "Kill player. @all for the Console only"
        usage: "/kill <player|@all>"
    vanish:
        description: "Turn On/Off invisibility mode"
        usage: "/vanish [player]"
    warp:
        description: "Teleport to warp"
        usage: "/warp <warp> [player]"
    fly:
        description: "Turn On/Off fly mode"
        usage: "/fly"
    help:
        description: "Get help"
        usage: "/help"