name: RichPit
authors: [KvaytG]
main: ru.kvaytg.richpit.RichPit
version: 1.0.0
api-version: 1.13
description: "Режим ThePit проекта RichWorld"
depend: [RichWorld, RichDonate, ColorAPI]
commands:
    up:
        description: "Improves the equipment"
        usage: "/up"
        aliases: ["upd", "upg"]
