name: RichAuth
author: KvaytG
main: ru.kvaytg.richauth.RichAuth
version: 1.0.0
api-version: 1.13
depend: [ColorAPI]
commands:
  link:
    description: "Linking Telegram to a Minecraft"
    usage: "/link <code>"
